# Generated by Django 4.1.3 on 2023-04-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_status_alter_deposite_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_payment_reference',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
    ]
