# Generated by Django 4.1.3 on 2023-05-08 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_paystack_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paystack_payment_reference',
            field=models.UUIDField(default=uuid.UUID('f75be462-f216-4e8e-8a7f-b1734a05c906')),
        ),
    ]
