# Generated by Django 4.1.3 on 2023-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_transaction_paystack_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paystack_payment_reference',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
